# Netlify configuration file

# Build settings
[build]
  # Directory with the built files (for static sites)
  publish = "public"
  
  # Functions directory
  functions = "functions"

# Redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Headers
[[headers]]
  # Define which paths this specific [[headers]] block will cover
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
