[build]
  command = "npm run build"
  publish = ".next"
  
[build.environment]
  NODE_VERSION = "16.14.0"
  
[dev]
  command = "npm run dev"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[plugins]]
  package = "@netlify/plugin-nextjs"
