[build]
  command = "npm run build"
  publish = ".next"
  
[build.environment]
  NODE_VERSION = "16.14.0"
  
[dev]
  command = "npm run dev"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-api/:splat"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs"
  status = 200
  
[[plugins]]
  package = "@netlify/plugin-nextjs"
