[build]
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/api/status"
  to = "/.netlify/functions/status"
  status = 200

[[redirects]]
  from = "/api/tiktok/account"
  to = "/.netlify/functions/tiktok-account"
  status = 200

[[redirects]]
  from = "/api/tiktok/post"
  to = "/.netlify/functions/tiktok-post"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
